### ISSUE TITLE
pam-migrator: [ERROR] Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by vyankatesh22** [Callum027/ipam-migrator#2]
Hi,
I tired to migrate phpipam to netbox but getting error below,

2020-08-20 13:38:18,567 ipam-migrator: [INFO] Searching for sections...
2020-08-20 13:38:18,740 ipam-migrator: [ERROR] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ipam_migrator-1.0.0-py3.6.egg/ipam_migrator/ipam_migrator.py", line 172, in main
    input_database = input_backend.database_read()
  File "/usr/local/lib/python3.6/site-packages/ipam_migrator-1.0.0-py3.6.egg/ipam_migrator/backend/phpipam.py", line 296, in database_read
    sections = self.sections_read() if read_prefixes or read_ip_addresses else None
  File "/usr/local/lib/python3.6/site-packages/ipam_migrator-1.0.0-py3.6.egg/ipam_migrator/backend/phpipam.py", line 331, in sections_read
    for data in self.api_read("sections"):
  File "/usr/local/lib/python3.6/site-packages/ipam_migrator-1.0.0-py3.6.egg/ipam_migrator/backend/phpipam.py", line 208, in api_read
    self.api_authenticate()
  File "/usr/local/lib/python3.6/site-packages/ipam_migrator-1.0.0-py3.6.egg/ipam_migrator/backend/phpipam.py", line 185, in api_authenticate
    obj = response.json()
  File "/usr/local/lib/python3.6/site-packages/requests-2.24.0-py3.6.egg/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-08-20 13:38:18,746 ipam-migrator: [DEBUG] stopping logger

**Comment by s2156945** [comment]
add /api to your ipam URL?
