### ISSUE TITLE
Problem importing phpipam to netbox

### ISSUE THREAD

**Issue by barto95100** [Callum027/ipam-migrator#3]
Hi,

thanks for your script :) 

I test to migrate my phpipam to netbox

phpipam version 1.4

When I test the migration :
ipam-migrator "http://10.xxx.yyy.zzz/api/migrator,phpipam,login,admin,gremzoihvnzemo$" --log-level DEBUG

the connection is ok but, when listed the vlan i received the error :
```2021-02-16 17:08:42,709 ipam-migrator: [INFO] Found 5324 IP addresses.
2021-02-16 17:08:42,709 ipam-migrator: [INFO] Searching for VLANs...
2021-02-16 17:08:42,718 ipam-migrator: [INFO] NOTE: 'vlans' controller root 'GET' method not supported by API endpoint, using iterative path (consider upgrading to phpIPAM 1.3+)```

and

```2021-02-16 17:09:22,583 ipam-migrator: [ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ipam_migrator-1.0.0-py3.8.egg/ipam_migrator/ipam_migrator.py", line 172, in main
    input_database = input_backend.database_read()
  File "/usr/local/lib/python3.8/dist-packages/ipam_migrator-1.0.0-py3.8.egg/ipam_migrator/backend/phpipam.py", line 311, in database_read
    vrfs = self.vrfs_read() if read_vrfs else None
  File "/usr/local/lib/python3.8/dist-packages/ipam_migrator-1.0.0-py3.8.egg/ipam_migrator/backend/phpipam.py", line 453, in vrfs_read
    raise NotImplementedError()
NotImplementedError```


do you have any idea of the problem ? 

thank you for your help :)

**Comment by s2156945** [comment]
Looks like this: https://github.com/Callum027/ipam-migrator/issues/1#issuecomment-568654230
